### ISSUE TITLE
md async error with gulp 4

### ISSUE THREAD

**Issue by ghosh** [helpers/helper-md#4] opened 2016-09-28 19:07 UTC
Hello,

Not sure, if I am doing this wrong but I am getting the following error when using it in a gulp 4 project. I am accessing the helper function through the handlebars-helpers package with gulp-hb.

Here is the error:-

```
md async helper expects callback to be a function. Did you mean to use `md.sync`?
```

I tried using the `{{markdown}}` helper and that is working fine. Not sure what is going wrong here.

**Comment by jonschlinkert** [comment] 2016-09-28 20:38
How are you registering the helper?

**Comment by ghosh** [comment] 2016-09-28 20:49
I'm registering through the [gulp-hb](https://github.com/shannonmoeller/gulp-hb) package via the `.helpers()` method.

```
.helpers(require('handlebars-layouts'))
```

It works for all the other helper functions, though the markdown methods were throwing errors, made them work with the fix mentioned here - https://github.com/assemble/handlebars-helpers/issues/222

This got the `{{markdown}}` helper working, but `{{md}}` is not working.

**Comment by jonschlinkert** [comment] 2016-09-28 21:08
Oh ok, since this issue was duplicated, and the issue is related to handlebars-helpers, I'll close this one and we can address this at assemble/handlebars-helpers#222

**Closed as completed by jonschlinkert** 2016-09-28 21:08 UTC

**Comment by ashleynolan** [comment] 2016-10-17 13:35
I’m having the same error appear when registering the helper through Gulp such that:

```
app.helper('md', require('helper-md'));
```

The `helper-markdown` helper works fine, but when I try using `{{ md "example-markdown-chunk.md" }}`, I get this error.

**Comment by jonschlinkert** [comment] 2016-10-17 14:00
> when registering the helper through Gulp such that:

Can you explain more? I'm not sure what this means

**Comment by ashleynolan** [comment] 2016-10-17 14:08
Sure.  All I meant was that I’m requiring Assemble (v0.17.1) through Gulp (v3.9.0), so my gulp setup looks like this essentially:

```
const assemble    = require('assemble');
const extname     = require('gulp-extname');
…
const app = assemble();
app.helper('markdown', require('helper-markdown'));
app.helper('md', require('helper-md'));

gulp.task('assemble', () => {

  //init assemble plugins
  app.enable('debugEngine');
  app.layouts(rootDir + '/layouts/*.{md,hbs}');
  app.partials(rootDir + '/partials/**/*.{md,hbs}');
  app.data(rootDir + config.dataDir + '/*.{json,yml}');
  app.option('layout', 'default');

  return app.src( rootDir + '/pages/**/*.{md,hbs}' )
                        .pipe( debug() )
                        .pipe( app.renderFile() )
                        .pipe( extname() )
                        .pipe( app.dest( statixDistDir ) );
}
```

For some reason all works exactly as I’d expect, except when including code to use the md helper in an `.hbs` file, which is when I get the error:

```
md async helper expects callback to be a function. Did you mean to use `md.sync`?
```

**Comment by jonschlinkert** [comment] 2016-10-17 14:11
got it, I think you're having the same issue addressed by https://github.com/assemble/handlebars-helpers/issues/222. We'll update that issue when progress is made

**Comment by ashleynolan** [comment] 2016-10-17 14:13
OK, thanks!

**Comment by blueowl0708** [comment] 2016-12-12 12:43
Hi @jonschlinkert 

I am also experiencing the issue described above by @ashleynolan and I don't think it's related to assemble/handlebars-helpers#222 (which refers to getting the helper to load - I've manually applied the fix in the PR for that bug and this leaves me with the error shown below).

Any attempt to use **helper-md** as per the doc results in the error message **md async helper expects callback to be a function. Did you mean to use `md.sync`?**

It looks like the helper is expecting a function to be passed in, but it's getting the context object - hence triggering this error message.

I think you may have fixed this already on helper-markdown: https://github.com/helpers/helper-markdown/commit/fa6f8578741c61f4affd0ac3a9926ca1a919abc8 but this fix wasn't applied to helper-md (or I'm not on the right track).  digging around I've seen references to you having a fix for helper-md at around the same time that commmit was made.

Thanks in advance and if you require any more information please let me know!
